/* ============================================================
 * 曙光教育智能系統 MVP · 慢荒宇宙
 * data.js — 交集資料庫種子內容（國中日常科學探索）
 * 每筆內容以多維標籤標記，對應企畫書附錄 A 維度代碼
 * ============================================================ */

const DIM_NAMES = {
  SUBJ: "學科領域",
  CONC: "核心概念",
  COGN: "認知層次",
  STAGE: "探索階段",
  LIFE: "生活情境",
  INTER: "互動形式",
  DIFF: "難度等級",
};

const SEED_CONTENTS = [
  {
    id: "c01",
    title: "為什麼從泳池起來，有風吹來特別冷？",
    summary: "離開泳池時，皮膚上的水開始蒸發，蒸發會從皮膚帶走熱量。風加速了蒸發，也加速了熱量散失，所以感覺特別冷。動手測量：比較有風與無風時皮膚溫度的下降速度。",
    source_type: "影片",
    duration: "4 分鐘",
    url: "https://example.org/lake/c01",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "蒸發" },
      { dim: "COGN", value: "觀察" },
      { dim: "STAGE", value: "引起好奇" },
      { dim: "LIFE", value: "浴室" },
      { dim: "INTER", value: "影片" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c02",
    title: "金屬湯匙為什麼比木筷子燙？",
    summary: "同樣放在熱湯裡，金屬湯匙摸起來更燙，不是因為它比較熱，而是因為金屬導熱快，熱量迅速傳到你的手。木筷導熱慢，所以感覺不燙。實驗：同時把金屬湯匙和木筷放入熱水，30 秒後比較溫度感受。",
    source_type: "文章",
    duration: "6 分鐘",
    url: "https://example.org/lake/c02",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "熱傳導" },
      { dim: "COGN", value: "預測" },
      { dim: "STAGE", value: "親自探索" },
      { dim: "LIFE", value: "廚房" },
      { dim: "INTER", value: "實驗" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c03",
    title: "橘子剝皮之後，竟然會沉下去？",
    summary: "整顆橘子放進水裡會浮起來，剝掉皮之後卻沉下去了。果皮裡有許多小氣室，讓整顆橘子的平均密度比水小。控制變因實驗：比較剝皮前後橘子的浮沉，思考「密度」到底在比什麼。",
    source_type: "互動模擬",
    duration: "10 分鐘",
    url: "https://example.org/lake/c03",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "密度" },
      { dim: "COGN", value: "變因控制" },
      { dim: "STAGE", value: "親自探索" },
      { dim: "LIFE", value: "廚房" },
      { dim: "INTER", value: "模擬" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c04",
    title: "筷子插進水杯，為什麼看起來彎了？",
    summary: "光從水中進入空氣時會改變行進方向，這就是折射。眼睛沿著折射後的直線回推，就以為筷子在水面處彎折了。觀察挑戰：改變筷子插入的角度，彎折看起來有什麼不同？",
    source_type: "影片",
    duration: "3 分鐘",
    url: "https://example.org/lake/c04",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "光折射" },
      { dim: "COGN", value: "觀察" },
      { dim: "STAGE", value: "引起好奇" },
      { dim: "LIFE", value: "家中" },
      { dim: "INTER", value: "影片" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c05",
    title: "紫甘藍汁的變色魔法：自製酸鹼指示劑",
    summary: "紫甘藍汁遇到酸會變紅、遇到鹼會變綠。用它測試家裡的檸檬汁、肥皂水、小蘇打水，把顏色變化記錄下來，你就擁有了一套天然的酸鹼檢測工具。注意：使用刀具與熱水時請成人陪同。",
    source_type: "文章",
    duration: "15 分鐘",
    url: "https://example.org/lake/c05",
    tags: [
      { dim: "SUBJ", value: "化學" },
      { dim: "CONC", value: "酸鹼" },
      { dim: "COGN", value: "變因控制" },
      { dim: "STAGE", value: "親自探索" },
      { dim: "LIFE", value: "廚房" },
      { dim: "INTER", value: "實驗" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c06",
    title: "窗邊的盆栽，為什麼總是歪向一邊？",
    summary: "植物的莖會朝著光的方向生長，這叫向光性。把盆栽轉 180 度，過幾天再觀察，它又會轉回來。預測挑戰：如果你只從左側照光，一週後莖會偏向哪一邊？",
    source_type: "文章",
    duration: "5 分鐘",
    url: "https://example.org/lake/c06",
    tags: [
      { dim: "SUBJ", value: "生物" },
      { dim: "CONC", value: "向光性" },
      { dim: "COGN", value: "預測" },
      { dim: "STAGE", value: "親自探索" },
      { dim: "LIFE", value: "家中" },
      { dim: "INTER", value: "閱讀" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c07",
    title: "手電筒為什麼會亮？拆解一個簡單電路",
    summary: "電池、燈泡、開關用導線連成一圈「通路」，電流才能流動，燈泡才會亮。互動模擬裡你可以自由接線：斷開任何一處，燈就滅了。思考：家裡的電燈開關，斷開的是哪一段？",
    source_type: "互動模擬",
    duration: "12 分鐘",
    url: "https://example.org/lake/c07",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "電路" },
      { dim: "COGN", value: "推理" },
      { dim: "STAGE", value: "親自探索" },
      { dim: "LIFE", value: "家中" },
      { dim: "INTER", value: "模擬" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c08",
    title: "變天之前，身體真的感覺得到嗎？認識鋒面",
    summary: "冷鋒通過前，氣壓下降、濕度上升，有些人會覺得關節痠、頭昏。鋒面是冷暖空氣的交界面，常帶來降雨和劇烈天氣變化。觀察任務：記錄一週的天氣預報，對照自己的身體感覺。",
    source_type: "文章",
    duration: "8 分鐘",
    url: "https://example.org/lake/c08",
    tags: [
      { dim: "SUBJ", value: "地球科學" },
      { dim: "CONC", value: "鋒面" },
      { dim: "COGN", value: "觀察" },
      { dim: "STAGE", value: "引起好奇" },
      { dim: "LIFE", value: "天氣" },
      { dim: "INTER", value: "閱讀" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c09",
    title: "月亮為什麼有圓缺？親手模擬月相變化",
    summary: "月相不是地球的影子，而是我們看到「被太陽照亮的那一半月球」的角度不同。月球繞地球一圈約 29.5 天，圓缺就跟著循環。用手電筒和乒乓球，你也能演出一次完整的月相秀。",
    source_type: "互動模擬",
    duration: "10 分鐘",
    url: "https://example.org/lake/c09",
    tags: [
      { dim: "SUBJ", value: "地球科學" },
      { dim: "CONC", value: "月相" },
      { dim: "COGN", value: "推理" },
      { dim: "STAGE", value: "延伸思考" },
      { dim: "LIFE", value: "戶外" },
      { dim: "INTER", value: "模擬" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c10",
    title: "吉他弦越粗，聲音越低？聲音的三要素",
    summary: "聲音有高低（音調）、大小（響度）、特色（音色）。弦越粗、越長、越鬆，振動越慢，音調越低。實驗：用不同粗細的橡皮筋做一把「橡皮筋吉他」，聽聽看音調的變化。",
    source_type: "文章",
    duration: "10 分鐘",
    url: "https://example.org/lake/c10",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "聲音" },
      { dim: "COGN", value: "變因控制" },
      { dim: "STAGE", value: "親自探索" },
      { dim: "LIFE", value: "家中" },
      { dim: "INTER", value: "實驗" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c11",
    title: "磁鐵隔著桌子，還吸得住迴紋針嗎？",
    summary: "磁力可以穿透木桌、紙張、塑膠等非磁性物質，但會隨著距離快速減弱。預測挑戰：隔著一本書、兩本書、三本書，磁鐵還吸得住迴紋針嗎？親手試試看你的預測準不準。",
    source_type: "影片",
    duration: "3 分鐘",
    url: "https://example.org/lake/c11",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "磁性" },
      { dim: "COGN", value: "預測" },
      { dim: "STAGE", value: "引起好奇" },
      { dim: "LIFE", value: "家中" },
      { dim: "INTER", value: "影片" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c12",
    title: "幾萬噸的船，為什麼不會沉？浮力的真相",
    summary: "船浮起來不是因為它輕，而是因為它排開的水夠多，受到的浮力等於船的重量。把一團黏土捏成碗狀，它就能浮起來——同樣的重量，形狀改變了命運。延伸思考：潛水艇要怎麼下潛和上浮？",
    source_type: "文章",
    duration: "9 分鐘",
    url: "https://example.org/lake/c12",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "浮力" },
      { dim: "COGN", value: "推理" },
      { dim: "STAGE", value: "延伸思考" },
      { dim: "LIFE", value: "交通" },
      { dim: "INTER", value: "閱讀" },
      { dim: "DIFF", value: "L3 進階" },
    ],
  },
  {
    id: "c13",
    title: "糖在熱水裡化得比較快？溶解速度大比拚",
    summary: "同樣一顆方糖，在熱水、冷水、攪拌、不攪拌的情況下，溶解速度完全不同。溫度越高，水分子運動越快，溶解就越快。變因控制練習：一次只改變一個條件，記錄溶解時間。",
    source_type: "文章",
    duration: "12 分鐘",
    url: "https://example.org/lake/c13",
    tags: [
      { dim: "SUBJ", value: "化學" },
      { dim: "CONC", value: "溶解" },
      { dim: "COGN", value: "變因控制" },
      { dim: "STAGE", value: "親自探索" },
      { dim: "LIFE", value: "廚房" },
      { dim: "INTER", value: "實驗" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c14",
    title: "腳踏車放著放著，為什麼生鏽了？",
    summary: "鐵生鏽是鐵和空氣中的氧、水發生化學反應，生成氧化鐵。乾燥的地方比較不容易生鏽，沿海特別容易。觀察任務：找找家裡三個生鏽的東西，推測它們生鏽的原因有什麼共同點。",
    source_type: "文章",
    duration: "5 分鐘",
    url: "https://example.org/lake/c14",
    tags: [
      { dim: "SUBJ", value: "化學" },
      { dim: "CONC", value: "氧化" },
      { dim: "COGN", value: "觀察" },
      { dim: "STAGE", value: "引起好奇" },
      { dim: "LIFE", value: "交通" },
      { dim: "INTER", value: "閱讀" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c15",
    title: "校園生態池裡，到底誰吃誰？",
    summary: "藻類被小魚吃，小魚被大魚吃，大魚死後分解者再把養分還給藻類——這就是食物鏈。畫出你家附近公園或校園的一條食物鏈，思考：如果其中一環消失了，會發生什麼事？",
    source_type: "Podcast",
    duration: "18 分鐘",
    url: "https://example.org/lake/c15",
    tags: [
      { dim: "SUBJ", value: "生物" },
      { dim: "CONC", value: "食物鏈" },
      { dim: "COGN", value: "推理" },
      { dim: "STAGE", value: "延伸思考" },
      { dim: "LIFE", value: "戶外" },
      { dim: "INTER", value: "討論" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c16",
    title: "曬衣服為什麼要攤開？蒸發的三個加速器",
    summary: "溫度、表面積、空氣流動，是影響蒸發速度的三個關鍵。衣服攤開（表面積大）、掛在通風處（空氣流動快）、曬太陽（溫度高），乾得最快。延伸挑戰：設計一個實驗，證明「表面積」真的有影響。",
    source_type: "文章",
    duration: "7 分鐘",
    url: "https://example.org/lake/c16",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "蒸發" },
      { dim: "COGN", value: "變因控制" },
      { dim: "STAGE", value: "延伸思考" },
      { dim: "LIFE", value: "家中" },
      { dim: "INTER", value: "討論" },
      { dim: "DIFF", value: "L3 進階" },
    ],
  },
  {
    id: "c17",
    title: "冷氣為什麼要裝在高處？熱空氣往上跑",
    summary: "熱空氣密度小會上升、冷空氣密度大會下沉，這叫對流。冷氣裝在高處，冷空氣下沉就能讓整間房間都涼。反過來想：暖氣應該裝在哪裡？",
    source_type: "文章",
    duration: "6 分鐘",
    url: "https://example.org/lake/c17",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "熱傳導" },
      { dim: "COGN", value: "推理" },
      { dim: "STAGE", value: "延伸思考" },
      { dim: "LIFE", value: "家中" },
      { dim: "INTER", value: "閱讀" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c18",
    title: "鏡子迷宮：光的反射大冒險",
    summary: "光遇到鏡子會反射，而且入射角等於反射角。利用兩面鏡子，你可以讓光「轉彎」照到原本照不到的地方。動手玩：用鏡子和手電筒，把光送進紙箱的死角。",
    source_type: "影片",
    duration: "4 分鐘",
    url: "https://example.org/lake/c18",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "光反射" },
      { dim: "COGN", value: "觀察" },
      { dim: "STAGE", value: "引起好奇" },
      { dim: "LIFE", value: "戶外" },
      { dim: "INTER", value: "影片" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c19",
    title: "胃藥為什麼能緩解胃酸過多？",
    summary: "胃藥裡的成分多半是弱鹼，可以中和過多的胃酸（鹽酸），讓胃不再那麼不舒服。但這只是治標——真正的原因可能是飲食習慣。延伸思考：為什麼不能長期依賴胃藥？",
    source_type: "Podcast",
    duration: "15 分鐘",
    url: "https://example.org/lake/c19",
    tags: [
      { dim: "SUBJ", value: "化學" },
      { dim: "CONC", value: "酸鹼" },
      { dim: "COGN", value: "推理" },
      { dim: "STAGE", value: "延伸思考" },
      { dim: "LIFE", value: "家中" },
      { dim: "INTER", value: "閱讀" },
      { dim: "DIFF", value: "L3 進階" },
    ],
  },
  {
    id: "c20",
    title: "葉子為什麼是綠的？光合作用的秘密",
    summary: "葉綠素吸收紅光和藍光，反射綠光，所以葉子看起來是綠的。光合作用把二氧化碳和水變成養分和氧氣，是地球上幾乎所有生命的能量來源。觀察：秋天葉子變黃變紅，是葉綠素在搞什麼名堂？",
    source_type: "影片",
    duration: "5 分鐘",
    url: "https://example.org/lake/c20",
    tags: [
      { dim: "SUBJ", value: "生物" },
      { dim: "CONC", value: "光合作用" },
      { dim: "COGN", value: "觀察" },
      { dim: "STAGE", value: "引起好奇" },
      { dim: "LIFE", value: "戶外" },
      { dim: "INTER", value: "影片" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c21",
    title: "跑步跑到喘不過氣，身體發生了什麼事？",
    summary: "劇烈運動時，肌肉需要大量能量，呼吸加快是為了吸入更多氧氣、排出更多二氧化碳。如果氧氣跟不上，身體會改用無氧呼吸，產生乳酸讓你覺得痠。延伸思考：為什麼運動員要練「有氧耐力」？",
    source_type: "Podcast",
    duration: "20 分鐘",
    url: "https://example.org/lake/c21",
    tags: [
      { dim: "SUBJ", value: "生物" },
      { dim: "CONC", value: "呼吸作用" },
      { dim: "COGN", value: "推理" },
      { dim: "STAGE", value: "延伸思考" },
      { dim: "LIFE", value: "運動" },
      { dim: "INTER", value: "閱讀" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c22",
    title: "公車急煞車，為什麼身體會往前倒？",
    summary: "物體會保持原來的運動狀態，這就是慣性。公車突然停下，腳跟著車停了，上半身卻還想往前衝。預測挑戰：車子突然加速時，身體會往哪倒？為什麼安全帶能救命？",
    source_type: "影片",
    duration: "3 分鐘",
    url: "https://example.org/lake/c22",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "慣性" },
      { dim: "COGN", value: "預測" },
      { dim: "STAGE", value: "引起好奇" },
      { dim: "LIFE", value: "交通" },
      { dim: "INTER", value: "影片" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c23",
    title: "鞋底為什麼要有紋路？摩擦力的日常應用",
    summary: "紋路增加鞋底和地面的摩擦力，讓你不容易滑倒。雨天走磁磚要特別小心，因為水膜讓摩擦力大減。實驗：比較光滑鞋底和有紋路鞋底，在濕毛巾上哪個比較不容易滑。",
    source_type: "文章",
    duration: "8 分鐘",
    url: "https://example.org/lake/c23",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "摩擦力" },
      { dim: "COGN", value: "變因控制" },
      { dim: "STAGE", value: "親自探索" },
      { dim: "LIFE", value: "運動" },
      { dim: "INTER", value: "實驗" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c24",
    title: "雲是怎麼形成的？天空的水循環之旅",
    summary: "地面水蒸發上升，遇到高空低溫凝結成小水滴，就成了雲。水滴長大變重，就落下來變成雨。互動模擬裡你可以調整溫度和濕度，親手「做」出一朵雲。",
    source_type: "互動模擬",
    duration: "12 分鐘",
    url: "https://example.org/lake/c24",
    tags: [
      { dim: "SUBJ", value: "地球科學" },
      { dim: "CONC", value: "水循環" },
      { dim: "COGN", value: "推理" },
      { dim: "STAGE", value: "延伸思考" },
      { dim: "LIFE", value: "天氣" },
      { dim: "INTER", value: "模擬" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c25",
    title: "地震波跑得有多快？比高鐵還快嗎？",
    summary: "地震的 P 波每秒可跑 6 公里左右，比高鐵快 20 倍以上。也因為波速快，距離震央遠的地方，反而有十幾秒的預警時間。觀察任務：下次收到地震警報時，數數看幾秒後才有感。",
    source_type: "文章",
    duration: "6 分鐘",
    url: "https://example.org/lake/c25",
    tags: [
      { dim: "SUBJ", value: "地球科學" },
      { dim: "CONC", value: "地震" },
      { dim: "COGN", value: "觀察" },
      { dim: "STAGE", value: "引起好奇" },
      { dim: "LIFE", value: "家中" },
      { dim: "INTER", value: "閱讀" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
  {
    id: "c26",
    title: "冬天脫毛衣，為什麼會有火花和劈啪聲？",
    summary: "毛衣和內衣摩擦，讓電荷分離累積在衣服表面，就是靜電。乾燥的冬天電荷不容易散去，累積到一定程度就會放電，產生小火花。觀察：夏天比較少發生，為什麼？",
    source_type: "影片",
    duration: "4 分鐘",
    url: "https://example.org/lake/c26",
    tags: [
      { dim: "SUBJ", value: "物理" },
      { dim: "CONC", value: "靜電" },
      { dim: "COGN", value: "觀察" },
      { dim: "STAGE", value: "引起好奇" },
      { dim: "LIFE", value: "家中" },
      { dim: "INTER", value: "影片" },
      { dim: "DIFF", value: "L1 入門" },
    ],
  },
  {
    id: "c27",
    title: "醃小黃瓜為什麼會出水？滲透作用上菜",
    summary: "鹽讓小黃瓜外面的濃度變高，裡面的水就透過細胞膜「滲透」出來。這跟植物根部吸水是同一個原理，只是方向相反。實驗：把小黃瓜片分別泡在鹽水和清水中，30 分鐘後比較軟硬。",
    source_type: "文章",
    duration: "10 分鐘",
    url: "https://example.org/lake/c27",
    tags: [
      { dim: "SUBJ", value: "生物" },
      { dim: "CONC", value: "滲透" },
      { dim: "COGN", value: "變因控制" },
      { dim: "STAGE", value: "親自探索" },
      { dim: "LIFE", value: "廚房" },
      { dim: "INTER", value: "實驗" },
      { dim: "DIFF", value: "L2 基礎" },
    ],
  },
];

/* ============================================================
 * 知識對決題庫：每題皆可對應到種子內容的標籤
 * ============================================================ */
const DUEL_QUESTIONS = [
  {
    id: "q01",
    tags: [
      { dim: "CONC", value: "蒸發" },
      { dim: "SUBJ", value: "物理" },
    ],
    question: "從泳池起來時，有風吹來會覺得特別冷，主要原因是？",
    options: [
      "風把身上的熱量直接吹走了",
      "皮膚上的水蒸發時帶走了熱量，風加速了蒸發",
      "泳池的水本來就比空氣冷",
      "身體離開水後毛細孔張開所以怕冷",
    ],
    answer: 1,
    feedback: "正確！蒸發需要吸熱，風加速蒸發＝加速從皮膚帶走熱量。這正是內容《為什麼從泳池起來，有風吹來特別冷？》的核心觀念。",
    misconception: "若選 A，要注意：風本身不帶走熱，關鍵是「蒸發吸熱」這個過程。",
  },
  {
    id: "q02",
    tags: [
      { dim: "CONC", value: "熱傳導" },
      { dim: "SUBJ", value: "物理" },
    ],
    question: "同樣放在熱湯裡，金屬湯匙摸起來比木筷子燙，真正的原因是？",
    options: [
      "金屬湯匙本身的溫度比木筷子高",
      "金屬比較重，所以比較燙",
      "金屬導熱快，熱量迅速傳到手上",
      "木筷子會吸熱，所以摸起來不燙",
    ],
    answer: 2,
    feedback: "正確！兩者溫度其實一樣，差別在「導熱速度」。金屬是熱的良導體，熱量一下子就傳到你的手。",
    misconception: "若選 A：記得「感覺燙」不等於「溫度高」，觸感還受到導熱快慢影響。",
  },
  {
    id: "q03",
    tags: [
      { dim: "CONC", value: "密度" },
      { dim: "SUBJ", value: "物理" },
    ],
    question: "整顆橘子會浮在水面，剝皮後卻沉了下去，最合理的解釋是？",
    options: [
      "果皮比較輕，剝掉後變重了",
      "果皮內有許多氣室，整顆橘子平均密度比水小",
      "橘子皮會吸水，所以整顆比較輕",
      "剝皮時果肉被壓縮，密度變大",
    ],
    answer: 1,
    feedback: "正確！關鍵是「平均密度」。果皮的氣室讓整顆橘子平均密度小於水，剝掉後密度超過水就下沉了。",
    misconception: "若選 A：重量不是重點，重點是「密度＝質量除以體積」的整體比較。",
  },
  {
    id: "q04",
    tags: [
      { dim: "CONC", value: "光折射" },
      { dim: "SUBJ", value: "物理" },
    ],
    question: "筷子斜插進水杯，看起來在水面處彎折了，這是因為？",
    options: [
      "水把筷子泡軟了",
      "光從水中進入空氣時改變了行進方向",
      "水面波動讓影像晃動",
      "杯子的玻璃有放大效果",
    ],
    answer: 1,
    feedback: "正確！這就是光的折射。眼睛沿直線回推光線方向，就誤以為筷子彎了。",
    misconception: "若選 C：水面平靜時折射現象依然存在，可見關鍵不是波動。",
  },
  {
    id: "q05",
    tags: [
      { dim: "CONC", value: "酸鹼" },
      { dim: "SUBJ", value: "化學" },
    ],
    question: "用紫甘藍汁測試家中的液體，檸檬汁會讓它變成什麼顏色？",
    options: ["綠色", "紅色", "藍色", "黃色"],
    answer: 1,
    feedback: "正確！紫甘藍汁是天然酸鹼指示劑：遇酸變紅、遇鹼變綠。檸檬汁是酸性，所以變紅。",
    misconception: "若選 A：綠色是遇到鹼性物質（如肥皂水）才會出現的顏色。",
  },
  {
    id: "q06",
    tags: [
      { dim: "CONC", value: "電路" },
      { dim: "SUBJ", value: "物理" },
    ],
    question: "手電筒要亮起來，必須滿足什麼條件？",
    options: [
      "電池夠新",
      "燈泡夠亮",
      "電池、燈泡、開關連成完整的通路",
      "導線越粗越好",
    ],
    answer: 2,
    feedback: "正確！電流需要完整的迴路（通路）才能流動。斷開任何一處，燈就滅了。",
    misconception: "若選 A：新電池電壓較高沒錯，但沒有通路，再新的電池燈也不會亮。",
  },
  {
    id: "q07",
    tags: [
      { dim: "CONC", value: "月相" },
      { dim: "SUBJ", value: "地球科學" },
    ],
    question: "月亮的圓缺變化，主要是因為？",
    options: [
      "地球的影子遮住了月亮",
      "月球繞地球公轉，我們看到被太陽照亮部分的比例不同",
      "月亮本身會發光，亮度有週期變化",
      "大氣層有時遮住月亮",
    ],
    answer: 1,
    feedback: "正確！月相是視角問題：月球被太陽照亮的永遠是同一半，但我們看到的角度隨公轉而變。地球影子造成的是「月食」，不是月相。",
    misconception: "若選 A：這是最常見的迷思！記得區分「月相」（視角變化）和「月食」（地球影子）。",
  },
  {
    id: "q08",
    tags: [
      { dim: "CONC", value: "浮力" },
      { dim: "SUBJ", value: "物理" },
    ],
    question: "幾萬噸的大船能浮在水面上，關鍵原因是？",
    options: [
      "船用的鋼鐵特別輕",
      "船排開的水夠多，受到的浮力等於船的重量",
      "海水浮力比淡水大很多",
      "船底是平的所以浮得起來",
    ],
    answer: 1,
    feedback: "正確！浮力的大小看「排開水的重量」。船體中空、體積大，排開的水夠多，浮力就能撐起整艘船。",
    misconception: "若選 A：鋼鐵密度比水大得多，重點從來不是材料輕，而是形狀讓它排開夠多水。",
  },
  {
    id: "q09",
    tags: [
      { dim: "CONC", value: "溶解" },
      { dim: "SUBJ", value: "化學" },
    ],
    question: "方糖在熱水中比在冷水中化得快，主要原因是？",
    options: [
      "熱水把糖燙融化了",
      "溫度越高，水分子運動越快，溶解越快",
      "熱水比較少雜質",
      "糖在熱水裡會膨脹",
    ],
    answer: 1,
    feedback: "正確！溫度升高，分子動能增加，水分子撞擊糖晶體的頻率和力道都變大，溶解自然加速。",
    misconception: "若選 A：溶解是分子層級的分散過程，不是「燙融化」。冰糖在冷水裡一樣會溶解，只是慢一點。",
  },
  {
    id: "q10",
    tags: [
      { dim: "CONC", value: "慣性" },
      { dim: "SUBJ", value: "物理" },
    ],
    question: "公車急煞車時，乘客的身體會往前倒，這是因為？",
    options: [
      "煞車的力把人往前推",
      "身體有慣性，會保持原來的運動狀態",
      "車廂地板太滑",
      "重心突然改變",
    ],
    answer: 1,
    feedback: "正確！這就是慣性：物體會保持原來的運動狀態。腳跟著車停下，上半身還想往前衝。",
    misconception: "若選 A：煞車的力作用在車輪和車身上，並沒有直接推人；讓人往前的是自己的慣性。",
  },
];

/* ============================================================
 * 三維雷達：範例拓荒者（座標僅內部計算用，前端只顯示距離）
 * X 知識廣度 / Y 認知深度 / Z 社會連結（0–100）
 * ============================================================ */
const PIONEERS = [
  { id: "me", name: "你", title: "見習拓荒者", x: 42, y: 35, z: 55, color: "#7dd3fc", isMe: true },
  { id: "p1", name: "觀星者 · 小月", title: "INFJ · 地球科學愛好者", x: 58, y: 48, z: 62, color: "#c4b5fd" },
  { id: "p2", name: "電路達人 · 阿哲", title: "物理實作派", x: 35, y: 70, z: 30, color: "#fbbf24" },
  { id: "p3", name: "生態旅人 · 小葵", title: "生物觀察家", x: 75, y: 40, z: 80, color: "#6ee7b7" },
  { id: "p4", name: "氣象觀測員 · 老K", title: "地球科學 × 數據派", x: 30, y: 55, z: 45, color: "#f9a8d4" },
];

/* 六種領土資源 */
const RESOURCES = [
  { id: "seed", name: "好奇種子", desc: "來自「引起好奇」階段內容，解鎖新探索主題", icon: "🌱" },
  { id: "eye", name: "觀察之眼", desc: "來自觀察、預測認知標籤，提升鏡心試煉準確度", icon: "👁️" },
  { id: "gear", name: "變因齒輪", desc: "來自變因控制認知標籤，解鎖互動模擬進階功能", icon: "⚙️" },
  { id: "spring", name: "心流之泉", desc: "來自心流相關內容，恢復專注度、提升防禦", icon: "💧" },
  { id: "web", name: "連結之網", desc: "來自共修羈絆相關標籤，請求夥伴支援", icon: "🕸️" },
  { id: "key", name: "陰影之鑰", desc: "來自陰影整合相關內容，解鎖深層自我探索", icon: "🗝️" },
];

/* 學習行為 → 領土效果（企畫書 §10.2） */
const ISLAND_ACTIONS = [
  { id: "explore", label: "完成一個科學探索主題", units: 1, reward: { seed: 1 }, hint: "＋1 領土 · ＋1 好奇種子" },
  { id: "myth", label: "在鏡心試煉中修正一個迷思", units: 1, reward: { eye: 1 }, hint: "＋1 領土 · ＋1 觀察之眼" },
  { id: "ask", label: "提出一個新問題", units: 0.5, reward: { seed: 1 }, hint: "＋0.5 領土 · ＋1 好奇種子" },
  { id: "quest", label: "完成一個任務市集委託", units: 2, reward: { gear: 1, spring: 1 }, hint: "＋2 領土 · ＋1 變因齒輪 · ＋1 心流之泉" },
  { id: "coresh", label: "與夥伴完成共修任務", units: 1.5, reward: { web: 1 }, hint: "＋1.5 領土 · ＋1 連結之網" },
];

const DAILY_CAP = 5;

/* 搜尋模式 */
const SEARCH_MODES = [
  { id: "strict", name: "嚴格交集", desc: "必須同時符合所有選定標籤" },
  { id: "weighted", name: "加權交集", desc: "符合越多標籤，排序越前面" },
  { id: "fuzzy", name: "模糊交集", desc: "允許部分符合，並顯示匹配度" },
];
